// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xnpvixeywrkcnpkqgkjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhucHZpeGV5d3JrY25wa3Fna2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzI1NjQsImV4cCI6MjA2ODE0ODU2NH0.5Ncu5xEeY7jQaJs_ksI_4NQ7XDZ7VwoDSwsB389VzH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);